[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29", features = ["osc52"] }
log = { version = "0.4", optional = true }
unicode-segmentation = "1.12"
unicode-width = "0.2"

[features]
default = []
log = ["dep:log"]
console_logger = ["log"]
